sudo apt install git
git config --global pull.ff only
git config --global user.name "Doug Paice"
git config --global user.email doug.paice@baralong.org
sudo apt install zsh
sudo chsh -s /usr/bin/zsh pi
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
sed -i 's/robbyrussell/kphoen/g' /home/pi/.zshrc
git clone https://github.com/baralong/pi-playpen.git ./dev/pi-playpen
sudo shutdown -r -t 30

